Забил решения ИП КР-3
bdemeshev/probability_hse_exams pull request #23
Opened 2019-04-30 08:56 UTC by alexreentovich

2019-04-30 18:11 UTC, olyagnilova requested changes

2019-04-30 18:11 UTC, olyagnilova commented on chapters/sol_kr_03_ip.tex
> +\begin{align*}\Cov(X_2-X_1,S_3)=\Cov(X_2-X_1,X_1+X_2+X_3)=\\=\Var(X_1)-\Var(X_1)=0\end{align*}
Окружение с \begin ... \end пишутся в несколько строк
Около первого '=' в каждой строчке нужен &, чтобы строки выравнивались именно по '='
В конце первой строки равно не нужно

2019-04-30 18:11 UTC, olyagnilova commented on chapters/sol_kr_03_ip.tex
> +\item[в)] Как известно из линейной алгебры, если вектор $X^-_1$ – проекция $X_1$ на $S_3$, a $X^{\perp}_1$ – соответствующая ортогональная составляющая, то $X^{\perp}_1=X_1-X^-_1=X_1-\alpha S_3$, при
Во всех случаях, когда в верхний или нижний индекс нужно написать более одного символа, их надо помещать в фигурные скобки, например X^{-1}

2019-04-30 18:11 UTC, olyagnilova commented on chapters/sol_kr_03_ip.tex
> +\[\langle X^{\perp}_1,S_3\rangle=\Cov(X^{\perp}_1,S_3)=\Cov(X^{\perp}_1,X_1-\alpha S_3)=0,\]
Выключные формулы тоже пишутся в несколько строк 
\\[
...
\\]

2019-04-30 18:11 UTC, olyagnilova commented on chapters/sol_kr_03_ip.tex
> +\[\langle X^{\perp}_1,S_3\rangle=\Cov(X^{\perp}_1,S_3)=\Cov(X^{\perp}_1,X_1-\alpha S_3)=0,\]
это нужно везде ниже поправить:)

2019-04-30 18:11 UTC, olyagnilova commented on chapters/sol_kr_03_ip.tex
> +\begin{align*}\Cov(X^-_1,X^-_2)=\Cov(X_1-\alpha S_3,X_2 - \beta S_3)=\\=-\alpha\Var(X_1)-\beta\Var(X_2)+3\alpha\beta\Var(X_1)
тут тоже надо разбить на несколько строк
перед первым '=' в каждой строке должен стоять &, а в конце строк висячего '=' быть не должно

2019-04-30 18:11 UTC, olyagnilova commented on chapters/sol_kr_03_ip.tex
> +\begin{align*}\Cov(X^-_1,X^-_2)=\Cov(X_1-\alpha S_3,X_2 - \beta S_3)=\\=-\alpha\Var(X_1)-\beta\Var(X_2)+3\alpha\beta\Var(X_1)
\begin{align*}...\end{align*} нужно везде поправить

2019-04-30 18:11 UTC, olyagnilova commented on chapters/sol_kr_03_ip.tex
> +откуда искомая частная корреляция равна -1/2.
Все числа должны быть в долларах $..$

2019-04-30 18:11 UTC, olyagnilova commented on chapters/sol_kr_03_ip.tex
> +\[L=\lambda e^{-\lambda x_1}\lambda e^{-\lambda x_2}\]
вот эти четыре выключные формулы можно записать в окружении align, выровняв всё по первому =

2019-04-30 18:11 UTC, olyagnilova commented on chapters/sol_kr_03_ip.tex
> +\[L=\lambda e^{-\lambda x_1}\lambda e^{-\lambda x_2}\prod^{10}_{i=3}e^{-30\lambda}\]
здесь то же самое: можно записать в align

2019-04-30 18:11 UTC, olyagnilova commented on chapters/sol_kr_03_ip.tex
> +\item У всех одинаковые шансы стать Самым Главным, что можно доказать методом математической индукции. Пусть всего метеорологов двое. Тогда, если у них монеты упали одной стороной, они оба выбывают,
Строчки текста тоже стоит разбивать по строкам, хотя бы каждое предложение с новой строки

2019-04-30 20:44 UTC, alexreentovich commented
Все поправил почти

2019-05-01 05:51 UTC, olyagnilova approved these changes

2019-05-01 05:51 UTC, merged