Решение 3 задачи кр-1 ип-части 2019-2020 года
bdemeshev/probability_hse_exams pull request #43
Opened 2019-11-12 17:07 UTC by elizacc

2019-11-16 10:25 UTC, bdemeshev requested changes

2019-11-16 10:25 UTC, bdemeshev commented on chapters/sol_kr_01_ip.tex
> +	\item[$a)$] Пусть $I -$ точка, куда приземлился Илон Маск, \\$G -$ точка, куда приземлилась Грета Тунберг.
только автоматическая нумерация :)
\item и всё :)
Пусть $I$ — точка, ... тире — это часть текста, а не формулы :) И тире длиннее дефиса :)

2019-11-16 10:25 UTC, bdemeshev commented on chapters/sol_kr_01_ip.tex
> +    \path[draw] (B) -- (D);
Восторг от картинки :)

2019-11-16 10:25 UTC, bdemeshev commented on chapters/sol_kr_01_ip.tex
> +	Тогда $f_L(x)~=~\left\{\begin{array}{rl}
вместо этого ужаса:
= \begin{cases}
2x, \text{ если } x \in [0,1] \\
0, \text{ иначе} \\
\end{cases}

2019-11-16 10:26 UTC, bdemeshev commented
pdf файл не надо коммитить :) только тех :)

2019-11-18 10:30 UTC, elizacc commented
Я что-то запуталась. Я сделала правки, но не очень понимаю как не создавая новый пулл реквест закинуть изменения сюда

2019-11-29 20:29 UTC, bdemeshev commented
Лиза, спасибо, я почистил текст и внёс в подборку :)

2019-11-29 20:29 UTC, closed without merging

2019-11-29 20:40 UTC, elizacc commented
Ура!